
name: EBeam Library Pcell Tests

on:
  push:
    branches:
      - master
      - Jasmina-Brar
      - Fariha
  pull_request:

jobs:
  pcell-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry 
        run: echo ${{ secrets.CR_PAT }} | podman login ghcr.io -u farihais --password-stdin
      
      - name: Pull gha_klayout image
        run: podman pull ghcr.io/farihais/gha_klayout:latest

      - name: Run podman container from image
        run: podman run -itd --name cloud_hosted_test -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --security-opt label=type:container_runtime_t ghcr.io/farihais/gha_klayout:latest

      - name: Copy pymacros folder to podman container
        run: podman cp $GITHUB_WORKSPACE/klayout/EBeam/pymacros cloud_hosted_test:/home/pymacros

      - name: Run KLayout Python script inside container and capture the exit code 
        run: podman exec cloud_hosted_test klayout -zz -r pymacros/EBeam_Lib_PCellTests.py || echo "KLAYOUT_EXIT_CODE=$?" >> $GITHUB_ENV
        continue-on-error: true

      - name: Stop the container and remove it 
        run: |
                podman stop cloud_hosted_test
                podman rm cloud_hosted_test
      - name: Fail the job if exit code is non-zero
        run: |
                if [ $KLAYOUT_EXIT_CODE -ne 0 ]; then
                        echo "KLayout exited with non-zero exit code"
                        exit 1
                fi 
