name: Run on new release 

on:
  release:
    types:
      - created
    repository:
      - 'jasminabrar/siepic_test'

jobs:     
  run-on-new-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
